In [1]:
import pandas as pd

# Data hasil cross-validation
metrics_bert = [
    {"Fold": 1, "Train Accuracy": 0.8884, "Val Accuracy": 0.8760, "Precision": 0.8880, "Recall": 0.8760, "F1 Score": 0.8748},
    {"Fold": 2, "Train Accuracy": 0.8869, "Val Accuracy": 0.8722, "Precision": 0.8761, "Recall": 0.8722, "F1 Score": 0.8717},
    {"Fold": 3, "Train Accuracy": 0.8870, "Val Accuracy": 0.8722, "Precision": 0.8790, "Recall": 0.8722, "F1 Score": 0.8711},
    {"Fold": 4, "Train Accuracy": 0.8908, "Val Accuracy": 0.8690, "Precision": 0.8836, "Recall": 0.8690, "F1 Score": 0.8661},
    {"Fold": 5, "Train Accuracy": 0.8871, "Val Accuracy": 0.8764, "Precision": 0.8830, "Recall": 0.8764, "F1 Score": 0.8756},
]

# Buat DataFrame
df_metrics_bert = pd.DataFrame(metrics_bert)

# Hitung rata-rata untuk tiap metrik (tanpa kolom "Fold")
mean_metrics_bert = df_metrics_bert.drop(columns=["Fold"]).mean()
mean_metrics_bert["Fold"] = "Mean"

# Tambahkan mean ke DataFrame
df_metrics_bert = pd.concat([df_metrics_bert, pd.DataFrame([mean_metrics_bert])], ignore_index=True)

# Tampilkan hasil
df_metrics_bert

   Fold  Train Accuracy  Val Accuracy  Precision   Recall  F1 Score
0     1         0.88840       0.87600    0.88800  0.87600   0.87480
1     2         0.88690       0.87220    0.87610  0.87220   0.87170
2     3         0.88700       0.87220    0.87900  0.87220   0.87110
3     4         0.89080       0.86900    0.88360  0.86900   0.86610
4     5         0.88710       0.87640    0.88300  0.87640   0.87560
5  Mean         0.88804       0.87316    0.88194  0.87316   0.87186

In [2]:
# Ubah index menjadi Fold 1, Fold 2, ..., Mean
df_metrics_bert.index = [f"Fold {i+1}" for i in range(len(df_metrics_bert)-1)] + ["Mean"]

# Drop kolom 'Fold'
df_metrics_bert = df_metrics_bert.drop(columns=['Fold'])

df_metrics_bert

        Train Accuracy  Val Accuracy  Precision   Recall  F1 Score
Fold 1         0.88840       0.87600    0.88800  0.87600   0.87480
Fold 2         0.88690       0.87220    0.87610  0.87220   0.87170
Fold 3         0.88700       0.87220    0.87900  0.87220   0.87110
Fold 4         0.89080       0.86900    0.88360  0.86900   0.86610
Fold 5         0.88710       0.87640    0.88300  0.87640   0.87560
Mean           0.88804       0.87316    0.88194  0.87316   0.87186

In [3]:
df_stats_bert = df_metrics_bert.describe().loc[['std']]
df_stats_bert

     Train Accuracy  Val Accuracy  Precision    Recall  F1 Score
std        0.001484      0.002746   0.004083  0.002746  0.003359

In [4]:
import pandas as pd

# Data hasil cross-validation
metrics_bilstm = [
    {"Fold": 1, "Train Accuracy": 0.9409, "Val Accuracy": 0.8127, "Precision": 0.8230, "Recall": 0.8127, "F1 Score": 0.8153},
    {"Fold": 2, "Train Accuracy": 0.9582, "Val Accuracy": 0.8394, "Precision": 0.8455, "Recall": 0.8394, "F1 Score": 0.8386},
    {"Fold": 3, "Train Accuracy": 0.9294, "Val Accuracy": 0.8511, "Precision": 0.8580, "Recall": 0.8511, "F1 Score": 0.8482},
    {"Fold": 4, "Train Accuracy": 0.9433, "Val Accuracy": 0.8411, "Precision": 0.8461, "Recall": 0.8411, "F1 Score": 0.8389},
    {"Fold": 5, "Train Accuracy": 0.9411, "Val Accuracy": 0.8502, "Precision": 0.8546, "Recall": 0.8502, "F1 Score": 0.8493},
]

# Buat DataFrame
df_metrics_bilstm = pd.DataFrame(metrics_bilstm)

# Hitung rata-rata untuk tiap metrik (tanpa kolom "Fold")
mean_metrics_bilstm = df_metrics_bilstm.drop(columns=["Fold"]).mean()
mean_metrics_bilstm["Fold"] = "Mean"

# Tambahkan mean ke DataFrame
df_metrics_bilstm = pd.concat([df_metrics_bilstm, pd.DataFrame([mean_metrics_bilstm])], ignore_index=True)

# Tampilkan hasil
df_metrics_bilstm

   Fold  Train Accuracy  Val Accuracy  Precision  Recall  F1 Score
0     1         0.94090        0.8127    0.82300  0.8127   0.81530
1     2         0.95820        0.8394    0.84550  0.8394   0.83860
2     3         0.92940        0.8511    0.85800  0.8511   0.84820
3     4         0.94330        0.8411    0.84610  0.8411   0.83890
4     5         0.94110        0.8502    0.85460  0.8502   0.84930
5  Mean         0.94258        0.8389    0.84544  0.8389   0.83806

In [5]:
# Ubah index menjadi Fold 1, Fold 2, ..., Mean
df_metrics_bilstm.index = [f"Fold {i+1}" for i in range(len(df_metrics_bilstm)-1)] + ["Mean"]

# Drop kolom 'Fold'
df_metrics_bilstm = df_metrics_bilstm.drop(columns=['Fold'])

df_metrics_bilstm

        Train Accuracy  Val Accuracy  Precision  Recall  F1 Score
Fold 1         0.94090        0.8127    0.82300  0.8127   0.81530
Fold 2         0.95820        0.8394    0.84550  0.8394   0.83860
Fold 3         0.92940        0.8511    0.85800  0.8511   0.84820
Fold 4         0.94330        0.8411    0.84610  0.8411   0.83890
Fold 5         0.94110        0.8502    0.85460  0.8502   0.84930
Mean           0.94258        0.8389    0.84544  0.8389   0.83806

In [6]:
df_stats_bilstm = df_metrics_bilstm.describe().loc[['std']]
df_stats_bilstm

     Train Accuracy  Val Accuracy  Precision    Recall  F1 Score
std          0.0092      0.013914   0.012212  0.013914  0.012233

In [7]:
from scipy.stats import ttest_rel
import pandas as pd

# Buang baris "Mean" berdasarkan index
df_bert = df_metrics_bert.drop(index="Mean")
df_bilstm = df_metrics_bilstm.drop(index="Mean")

# Pastikan data dalam bentuk float
df_bert = df_bert.astype(float)
df_bilstm = df_bilstm.astype(float)

# Kolom metrik yang ingin diuji
metrics = df_bert.columns  # atau tuliskan manual: ["Train Accuracy", "Val Accuracy", ...]

# Lakukan t-test
results = {}
for metric in metrics:
    t_stat, p_value = ttest_rel(df_bert[metric], df_bilstm[metric])
    results[metric] = {"t-stat": t_stat, "p-value": p_value}

# Tampilkan hasil
t_test_results = pd.DataFrame(results).T
t_test_results

                   t-stat   p-value
Train Accuracy -11.669254  0.000308
Val Accuracy     4.569926  0.010261
Precision        4.805295  0.008615
Recall           4.569926  0.010261
F1 Score         5.096700  0.006999